### ISSUE TITLE
Add Markus to the repo

### ISSUE THREAD

**Issue by bobarna** [AoGao-Kedoka/bouncebounce#1]

**Comment by kSDOT** [comment]
Markus Gumbart - ge25lim@mytum.de

**Comment by AoGao-Kedoka** [comment]
is there updates to this issue @kSDOT? cause I was not in the question session today...

**Comment by kSDOT** [comment]
I think the Q&A with our tutor is on Thursdays@16:00-17:00

**Comment by AoGao-Kedoka** [comment]
Oh Sorry for that, I thought it was on Tuesday😂
