### ISSUE TITLE
Set a time for the next meeting

### ISSUE THREAD

**Issue by kSDOT** [AoGao-Kedoka/bouncebounce#2]

**Comment by bobarna** [comment]
The first deadline is __next Monday__ (15. 11.)

**Comment by kSDOT** [comment]
Available time slots:
Saturday: 10:00 - 15:00
Sunday:   10:00 - 18:00
Monday:  16:00 - 20:00
Good for @bobarna @kSDOT  @AoGao-Kedoka 
@Nafay987, let us know what time works for you.

**Comment by AoGao-Kedoka** [comment]
So the next meeting will be on next monday right?

**Comment by kSDOT** [comment]
Monday would be an option too, can everyone comment when they want to meet? For me Saturday at 10:00 would be ideal, Sunday at 10:00 would be great too.

**Comment by AoGao-Kedoka** [comment]
I have a small meeting on Saturday from 13 -14. Otherwise I'm ok with **Saturday, Sunday and Monday after 15:30**

**Comment by kSDOT** [comment]
Next meeting set for:
Monday 15:30
